name: WREPL CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Build uberjar
      run: lein uberjar
    - name: Release on tag
      uses: svenstaro/upload-release-action@v1-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: target/wrepl-*-standalone.jar
        tag: ${{ github.ref }}
        overwrite: true
